nacos_address: 127.0.0.1:8848
seata_address: 127.0.0.1:8091

spring:
  application:
    name: demo-stock
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_address}
      config:
        server-addr: ${nacos_address}
    loadbalancer:
      nacos:
        enabled: true
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
server:
  port: 8082

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      demo-stock-group: default
    grouplist:
      default: ${seata_address}