spring:
  application:
    name: demo-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      nacos:
        enabled: true
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
server:
  port: 8081


seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      demo-order.group: default
    grouplist:
      default: 127.0.0.1:7091
